<?php
use App\Cars;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cars')->insert([
            [
                'id' => 1,
                'brand' => 'Volkswagen',
                'model' => 'Golf IV ',
                'image' => 'public/kvyAZPPeSg6p1Dx8bHa0PkQLnpAaD2IeXxH94loA.jpg',
                'year' => 1998,
                'capacity' => 4,
                'doors' => 4,
                'engine' => 'Diesel',
                'gearbox' => 'Manual',
                'status' => 'free',
                'hire_cost' => 24,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),

            ],
            [
                'id' => 2,
                'brand' => 'Audi',
                'model' => 'A3',
                'image' => 'public/audi_a3_v8.jpg',
                'year' => 2016,
                'capacity' => 5,
                'doors' => 4,
                'engine' => 'Gasoline',
                'gearbox' => 'Automatic',
                'status' => 'free',
                'hire_cost' => 55,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),

            ],
            [
                'id' => 3,
                'brand' => 'Audi',
                'model' => 'A6',
                'image' => 'public/audi_a6.jpg',
                'year' => 20019,
                'capacity' => 6,
                'doors' => 4,
                'engine' => 'Diesel',
                'gearbox' => 'Automatic',
                'status' => 'free',
                'hire_cost' => 1,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 4,
                'brand' => 'Jeep',
                'model' => 'Cherokee',
                'image' => 'public/jeep_cherokee.jpg',
                'year' => 2007,
                'capacity' => 5,
                'doors' => 4,
                'engine' => 'Gasoline',
                'gearbox' => 'Manual',
                'status' => 'free',
                'hire_cost' => 1,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 5,
                'brand' => 'Tesla',
                'model' => 'Model 3',
                'image' => 'public/tesla_model_3.jpg',
                'year' =>  2017,
                'capacity' => 7,
                'doors' => 4,
                'engine' => 'Electric',
                'gearbox' => 'Automatic',
                'status' => 'free',
                'hire_cost' => 25,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 6,
                'brand' => 'Tesla',
                'model' => 'Model S',
                'image' => 'public/tesla_model_S.jpg',
                'year' => 2020,
                'capacity' => 8,
                'doors' => 4,
                'engine' => 'Electric',
                'gearbox' => 'Automatic',
                'status' => 'free',
                'hire_cost' => 32,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 7,
                'brand' => 'Tesla',
                'model' => 'Model X',
                'image' => 'public/tesla_model_X.jpg',
                'year' => 2019,
                'capacity' => 8,
                'doors' => 4,
                'engine' => 'Electric',
                'gearbox' => 'Automatic',
                'status' => 'free',
                'hire_cost' => 15,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 8,
                'brand' => 'Tesla',
                'model' => 'Model Y',
                'image' => 'public/tesla_model_Y.jpg',
                'year' => 2020,
                'capacity' => 7,
                'doors' => 4,
                'engine' => 'Electric',
                'gearbox' => 'Automatic',
                'status' => 'free',
                'hire_cost' => 21,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 9,
                'brand' => 'Toyota',
                'model' => 'Supra',
                'image' => 'public/toyota-supra.jpg',
                'year' => 2020,
                'capacity' => 4,
                'doors' => 2,
                'engine' => 'Gasoline',
                'gearbox' => 'Automatic',
                'status' => 'free',
                'hire_cost' => 54,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 10,
                'brand' => 'Toyota',
                'model' => 'SUV',
                'image' => 'public/toyota.jpg',
                'year' => 2016,
                'capacity' => 8,
                'doors' => 4,
                'engine' => 'Diesel',
                'gearbox' => 'Manual',
                'status' => 'free',
                'hire_cost' => 24,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 11,
                'brand' => 'Mercedes',
                'model' => 'C class',
                'image' => 'public/mercedes_car1.jpg',
                'year' => 2018,
                'capacity' => 2,
                'doors' => 4,
                'engine' => 'Gasoline',
                'gearbox' => 'Automatic',
                'status' => 'free',
                'hire_cost' => 36,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 11,
                'brand' => 'Volkswagen',
                'model' => 'Golf VII',
                'image' => 'public/golf_7_2019.jpg',
                'year' => 2019,
                'capacity' => 4,
                'doors' => 4,
                'engine' => 'Gasoline',
                'gearbox' => 'Automatic',
                'status' => 'free',
                'hire_cost' => 44,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 11,
                'brand' => 'BMW',
                'model' => '630',
                'image' => 'public/bmw-630.2018.jpg',
                'year' => 2019,
                'capacity' => 4,
                'doors' => 4,
                'engine' => 'Gasoline',
                'gearbox' => 'Automatic',
                'status' => 'free',
                'hire_cost' => 44,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],



        ]);
    }
}



